kind: pipeline
type: docker
name: consorcio-front-pipeline

trigger:
  branch:
    - main
  event:
    - push
    - pull_request

steps:
  # Passo 1: Instalar dependências com yarn
  - name: install-dependencies
    image: node:20-alpine # Usando a mesma versão do seu Dockerfile
    commands:
      # Trocado 'npm install' por 'yarn install'
      - yarn install --frozen-lockfile
    volumes:
      - name: cache
        path: /drone/src/node_modules


  # Passo 2: Rodar testes e lint com yarn
  - name: test-and-lint
    image: node:20-alpine
    depends_on: [install-dependencies]
    commands:
      # Adapte os comandos se você usar nomes diferentes nos seus scripts
      - yarn lint
      - yarn test -- --watch=false --browsers=ChromeHeadless
    volumes:
      - name: cache
        path: /drone/src/node_modules

  # Passo 4: Construir e publicar a imagem Docker com Nginx
  - name: build-and-publish-image
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      registry: docker.io
      repo: k3rb3rdock/consorcio-front
      tags:
        - latest
        - ${DRONE_COMMIT_SHA:0:7}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - main
      event:
        - push

  - name: deploy-to-k8s
    image: appleboy/drone-kubectl
    settings:
      kube_config:
        from_secret: KUBE_CONFIG
      commands:
        - kubectl apply -f k8s/dev.yaml
        - kubectl set image deployment/consorcio-front-deployment consorcio-front-container=k3rb3rdock/consorcio-front:${DRONE_COMMIT_SHA:0:7} -n dev
    when:
      branch:
        - main
      event:
        - push

