kind: pipeline
type: docker
name: consorcio-front-pipeline

trigger:
  branch: [main]
  event: [push]

steps:
  - name: install-and-test
    image: node:20-alpine
    commands:
      - yarn install --frozen-lockfile

  - name: build-and-publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      registry: docker.io
      repo: k3rb3rdock/consorcio-front
      tags:
        - ${DRONE_COMMIT_SHA:0:8} # Usar um tag único é melhor que 'latest'
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password


  - name: deploy-to-k8s
    image: alpine/k8s:1.29.2  # Imagem oficial e confiável
    environment:
      KUBE_CONFIG:
        from_secret: kube_config  # Corrigir o nome do secret também
    commands:
      - mkdir -p ~/.kube
      - echo "$KUBE_CONFIG" > ~/.kube/config
      - kubectl set image deployment/consorcio-front-deployment consorcio-front-container=k3rb3rdock/consorcio-front:${DRONE_COMMIT_SHA:0:8} -n dev
