server {
  listen 80;
  server_name localhost;

  # Novo caminho raiz para os arquivos no Alpine Linux
  root /var/www/localhost/htdocs;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }
}
